### ISSUE TITLE
a problem

### ISSUE THREAD

**Issue by roy-lei** [ritmininglab/A-Dynamic-Meta-Learning-Model-for-Time-Sensitive-Cold-Start-Recommendations#2]
Hi! I'm very interested in your work but when I'm trying to redo your experiment, I found that the "{}/embedding/movie_emb_32.pkl" seems don't exist.
This file is in the movielens/proposed_model.py, line 208. I don't konw wether it refers to some other file or not, I'm quiet confusing.

**Comment by kpn3569** [comment]
This file should be replaced by ./movielens/f_movie_dict.pkl

**Comment by roy-lei** [comment]
ok, thank you!
