### ISSUE TITLE
'for user in test_user:' in 'movielens/proposed_model'

### ISSUE THREAD

**Issue by roy-lei** [ritmininglab/A-Dynamic-Meta-Learning-Model-for-Time-Sensitive-Cold-Start-Recommendations#3]
![image](https://user-images.githubusercontent.com/81239693/189857844-f8496843-51eb-4e78-9982-1e684db88128.png)
Hi, I'm a little confused about this code. It's in the 'movielens/proposed_model.py', line 291.
I think it should be `for user in tt_user:` rather than `for user in test_user:`. In the coresponding postion of other 'proposed_model.py', the code is `for user in tt_user:`. I wonder wether it should be `for user in tt_user:` or `for user in test_user:` in this file.

**Comment by kpn3569** [comment]
Yes. This is a typo and it should be the total_user (tt_user) for the RNN model.  Will update it. Thanks!

**Comment by roy-lei** [comment]
ok, thank you!
